name: monk

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # dependencies
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SMOKER_KEY }}
      - name: Setup Go environment
        uses: actions/setup-go@v2-beta

      # git setup
      - name: Setup repository
        run: |
          git config user.email "monk@davidepucci.it" 
          git config user.name "Amanuensis Monk"

      # zeus setup
      - name: Download and configure Zeus
        run: |
          go get -v github.com/dreadl0ck/zeus@45d665d962
        env:
          GO111MODULE: on

      # effective action
      - name: Run packages update check
        run: |
          zeus wikis
          if ! git diff-index --quiet HEAD -- src/wikis; then
            git commit -m "src: wikis: flush" src/wikis
          fi
          git push