name: monk

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      commit_msg: "src: wikis: flush"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_ACTIONS_DAVIDEPUCCI }}

      - name: Setup repository
        run: |
          git config user.email "monk@davidepucci.it" 
          git config user.name "Amanuensis Monk"

      - name: Run packages update check
        run: |
          make wikis
          if ! git diff-index --quiet HEAD -- src/wikis; then
            git commit -m "${commit_msg}" src/wikis
          fi

      - name: Strip wikis flushes
        run: |
          while true; do
            git log --oneline -2 | tail -1 | awk "/${commit_msg}\$/ {print \$1}" | xargs -r git commit --amend --fixup
            [ $(git log --oneline -1 | head -1 | grep -c 'fixup!') -ne 1 ] && break
            git rebase -i --autostash --autosquash HEAD~2
          done
        env:
          GIT_SEQUENCE_EDITOR: ":"

      - name: Push repository
        run: |
          git push -f